config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :things
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_many :comments

  scope :latest, lambda { all.limit(9).order("id DESC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  def new
    form Thing::Create
  end

  def create
    run Thing::Create do |op|
      return redirect_to op.model
    end
    render action: :new
  end

  def edit
    form Thing::Update
    render action: :new
  end

  def update
    run Thing::Update do |op|
      return redirect_to op.model
    end
    render action: new
  end

  def show
    present Thing::Update
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.row
  %h3
    Welcome to Gemgem!

.row
  - things = Thing.latest
  = concept("thing/cell", collection: things, last: things.last)

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Gemgem - Feedback for a better world.'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Rails Foundation'}"}
    = stylesheet_link_tag 'application', media: 'all'
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/things/new.html.haml
= simple_form_for @form do |f|
  = f.input :name, readonly: @form.readonly?(:name)
  = f.input :description

  = f.submit

app/views/things/show.html.haml
.header
  %h1
    #{@model.name}
    = link_to "Edit", edit_thing_path(@model)

#{@model.description}